### ISSUE TITLE
How to do ethereum internal transaction

### ISSUE THREAD

**Issue by shweta037** [Diwala/eth-internal-transaction-disecter#4]
How can we do internal ethereum transaction using node js code...Is there any example code for doing such.....

**Comment by vongohren** [comment]
So this is not for doing an internal transaction, but to disect internal transacitons. It is not used by us anymore, but you can use this lib in node like this: https://github.com/Diwala/eth-internal-transaction-disecter/tree/master/examples/node-js

**Comment by shweta037** [comment]
> So this is not for doing an internal transaction, but to disect internal transacitons. It is not used by us anymore, but you can use this lib in node like this: https://github.com/Diwala/eth-internal-transaction-disecter/tree/master/examples/node-js

Thanks for the quick reply..So is there anything then for automatic transaction of coins and token...
Thanks in advance..

**Comment by vongohren** [comment]
@shweta037 I think what you are looking for is something you can find in the ethereum space as a service. Im just not sure what you are trying to achieve. Because there are multiple ways to send coins, but automatically makes it a bit more difficult. Dependent if you are holding the private key, or doing it on behalf of someone.
If you hold the private key you can just use https://web3js.readthedocs.io/en/1.0/ and do a transaction when some action happens.

If you dont hold the private key, you should start looking into this kind of transactions
https://medium.com/coinmonks/gasless-transactions-f75382095c4f

**Comment by shweta037** [comment]
> @shweta037 I think what you are looking for is something you can find in the ethereum space as a service. Im just not sure what you are trying to achieve. Because there are multiple ways to send coins, but automatically makes it a bit more difficult. Dependent if you are holding the private key, or doing it on behalf of someone.
> If you hold the private key you can just use https://web3js.readthedocs.io/en/1.0/ and do a transaction when some action happens.
> 
> If you dont hold the private key, you should start looking into this kind of transactions
> https://medium.com/coinmonks/gasless-transactions-f75382095c4f

Sir i am actually a developer and trying to create a function for automatic transaction ,suppose we have deposited some amount in our address that amount should be automatically transferred to another address.And when we are trying to send any token the fee of 0.006eth should be deduct automatically...

**Comment by vongohren** [comment]
@shweta037 I believe you are a developer, but then you have to communicate your problem properly so I can help you 😁

Yeah that is pretty easy, just doing a transaction in the backend with web3.js, that estimates the fee and pulls it out.

But short, this lib doesnt handle that.
